# этот плагин сделан чисто для братишки Марселя
# так что, если юзаете плагин, то знаете, МАРС СЛЕДИТ ЗА ВАМИ

items:
  STONE_PICKAXE: # материал предмета, можно хоть книгу или булыжник поставить
    FARMING: 5 # минимальный скил для юза предмета

messages:
  you-cant: "&#FF0000Тебе необходимо иметь навык {skill_name} больше чем {skill}!" # {skill_name} это имя скилла, типо FARMING, {skill} это число

replace:
  FARMING: "&eфермерство&r"